[project]
name = "autoscraper"
version = "0.1.0"
description = "Your custom autoscraper project"
authors = [{name = "Soham"}]
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
